'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import './tennis-duel.css';
import { trackGame } from '../lib/analytics';

type Player = { x: number; y: number; vy: number; score: number };
type Ball = { x: number; y: number; vx: number; vy: number; bounces: number };

const W=900,H=520,FLOOR=410,WIN=7;
const initialPlayers=():[Player,Player]=>[{x:170,y:FLOOR-72,vy:0,score:0},{x:W-200,y:FLOOR-72,vy:0,score:0}];
const initialBall=():Ball=>({x:W/2,y:250,vx:4.4,vy:-4.8,bounces:0});

export default function TennisDuel(){
 const canvas=useRef<HTMLCanvasElement>(null); const keys=useRef(new Set<string>()); const p=useRef(initialPlayers()); const b=useRef(initialBall()); const phase=useRef<'ready'|'play'|'over'>('ready'); const raf=useRef<number>();
 const [state,setState]=useState<'ready'|'play'|'over'>('ready'); const [score,setScore]=useState<[number,number]>([0,0]); const [winner,setWinner]=useState(0); const [msg,setMsg]=useState('First to 7 points wins');
 const reset=useCallback((start=true)=>{p.current=initialPlayers();b.current=initialBall();phase.current=start?'play':'ready';setState(start?'play':'ready');setScore([0,0]);setWinner(0);setMsg('First to 7 points wins');trackGame(start?'game_restart':'game_open','tennis-duel')},[]);
 const serve=useCallback((who:1|2)=>{if(phase.current!=='play')return;const pl=p.current[who-1];const bb=b.current;if(Math.hypot(bb.x-(pl.x+18),bb.y-(pl.y+12))<72){bb.vx=who===1?7.2:-7.2;bb.vy=-7;bb.bounces=0;setMsg(`PLAYER ${who} RETURNS!`)}},[]);
 useEffect(()=>{const d=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();if(['a','d','w','f','arrowleft','arrowright','arrowup','l','enter',' '].includes(k))e.preventDefault();keys.current.add(k);if(k==='f')serve(1);if(k==='l')serve(2);if((k==='enter'||k===' ')&&phase.current==='over')reset(true)};const u=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());addEventListener('keydown',d);addEventListener('keyup',u);return()=>{removeEventListener('keydown',d);removeEventListener('keyup',u)}},[reset,serve]);
 useEffect(()=>{trackGame('game_open','tennis-duel');const c=canvas.current,ctx=c?.getContext('2d');if(!c||!ctx)return;let last=performance.now();const loop=(now:number)=>{const dt=Math.min(2,(now-last)/16.67);last=now;const ps=p.current,bb=b.current;if(phase.current==='play'){const k=keys.current;ps[0].x+=(k.has('d')?5:0)-(k.has('a')?5:0);ps[1].x+=(k.has('arrowright')?5:0)-(k.has('arrowleft')?5:0);ps[0].x=Math.max(45,Math.min(W/2-65,ps[0].x));ps[1].x=Math.max(W/2+45,Math.min(W-65,ps[1].x));ps[0].vy+=.42*dt;ps[1].vy+=.42*dt;ps[0].y+=ps[0].vy*dt;ps[1].y+=ps[1].vy*dt;for(const pl of ps)if(pl.y>FLOOR-72){pl.y=FLOOR-72;pl.vy=0}if(k.has('w')&&ps[0].y>=FLOOR-72)ps[0].vy=-8;if(k.has('arrowup')&&ps[1].y>=FLOOR-72)ps[1].vy=-8;
 bb.vy+=.28*dt;bb.x+=bb.vx*dt;bb.y+=bb.vy*dt;if(bb.y>FLOOR-12){bb.y=FLOOR-12;bb.vy*=-.72;bb.bounces++}if(bb.x<24){ps[1].score++;bb.x=W/2;bb.y=230;bb.vx=4.4;bb.vy=-5;bb.bounces=0;setMsg('POINT PLAYER 2')}if(bb.x>W-24){ps[0].score++;bb.x=W/2;bb.y=230;bb.vx=-4.4;bb.vy=-5;bb.bounces=0;setMsg('POINT PLAYER 1')}for(let i=0;i<2;i++){const pl=ps[i],dist=Math.hypot(bb.x-(pl.x+18),bb.y-(pl.y+15));if(dist<48&&((i===0&&bb.vx<0)||(i===1&&bb.vx>0))){bb.vx=i===0?Math.abs(bb.vx)+.35:-Math.abs(bb.vx)-.35;bb.vy=-Math.abs(bb.vy)-1.1;bb.bounces=0;setMsg(`PLAYER ${i+1} HITS!`)}}if(ps[0].score>=WIN||ps[1].score>=WIN){const w=ps[0].score>=WIN?1:2;phase.current='over';setState('over');setWinner(w);setMsg(`PLAYER ${w} WINS!`);trackGame('game_finish','tennis-duel',{winner:w})}setScore([ps[0].score,ps[1].score])}
 ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#101b2b');g.addColorStop(1,'#071019');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#17452f';ctx.fillRect(0,FLOOR,W,H-FLOOR);ctx.strokeStyle='#d8f6e5';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(W/2,FLOOR);ctx.lineTo(W/2,100);ctx.stroke();ctx.strokeStyle='#6edb9d';ctx.lineWidth=4;ctx.strokeRect(24,90,W-48,FLOOR-90);ctx.strokeStyle='rgba(255,255,255,.2)';ctx.beginPath();ctx.moveTo(24,250);ctx.lineTo(W-24,250);ctx.stroke();
 psDraw(ctx,ps[0],1);psDraw(ctx,ps[1],2);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(bb.x,bb.y,11,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#b7f34a';ctx.stroke();raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>{if(raf.current)cancelAnimationFrame(raf.current)}},[]);
 return <main className="tennis-page"><div className="tennis-shell"><header><a href="/gamehub/">← GAMEHUB</a><span>2 PLAYER · TENNIS</span><button onClick={()=>reset(true)}>REMATCH</button></header><div className="tennis-score"><div><small>P1</small><strong>{score[0]}</strong></div><b>VS</b><div><small>P2</small><strong>{score[1]}</strong></div></div><div className="tennis-court"><canvas ref={canvas} width={W} height={H}/>{state!=='play'&&<div className="tennis-overlay"><span>{state==='ready'?'🏆':winner===1?'🥇':'🥈'}</span><h1>{state==='ready'?'TENNIS DUEL':`PLAYER ${winner} WINS`}</h1><p>{msg}</p><button onClick={()=>reset(true)}>{state==='ready'?'START MATCH':'PLAY AGAIN'}</button></div>}</div><div className="tennis-controls"><div><strong>P1</strong><span>A / D MOVE</span><span>W JUMP</span><span>F HIT</span></div><div><strong>P2</strong><span>← / → MOVE</span><span>↑ JUMP</span><span>L HIT</span></div></div><p className="tennis-tip">Get under the ball, hit it early, and force your friend to chase the angle.</p></div></main>
}
function psDraw(ctx:CanvasRenderingContext2D,p:Player,who:number){ctx.fillStyle=who===1?'#b7f34a':'#78e4ff';ctx.beginPath();ctx.roundRect(p.x,p.y,36,62,12);ctx.fill();ctx.fillStyle='#071019';ctx.beginPath();ctx.arc(p.x+18,p.y-7,14,0,Math.PI*2);ctx.fill();ctx.strokeStyle=ctx.fillStyle;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(p.x+(who===1?30:6),p.y+22);ctx.lineTo(p.x+(who===1?48:-12),p.y+8);ctx.stroke()}
