'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import './asteroid-blaster.css';
import {trackGame} from '../lib/analytics';

type State='ready'|'play'|'over';
type Asteroid={x:number;y:number;vx:number;vy:number;r:number};
type Bullet={x:number;y:number;vy:number};
const W=900,H=520;
export default function AsteroidBlaster(){
 const canvas=useRef<HTMLCanvasElement>(null),keys=useRef(new Set<string>()),ship=useRef({x:W/2}),rocks=useRef<Asteroid[]>([]),bullets=useRef<Bullet[]>([]),scoreRef=useRef(0),state=useRef<State>('ready'),spawn=useRef(0),raf=useRef<number>();
 const [ui,setUi]=useState<State>('ready'),[score,setScore]=useState(0),[best,setBest]=useState(0);
 const reset=useCallback((start=true)=>{ship.current={x:W/2};rocks.current=[];bullets.current=[];scoreRef.current=0;spawn.current=0;state.current=start?'play':'ready';setUi(state.current);setScore(0);trackGame(start?'game_restart':'game_open','asteroid-blaster')},[]);
 const fire=useCallback(()=>{if(state.current!=='play'){reset(true);return}bullets.current.push({x:ship.current.x,y:H-70,vy:-10})},[reset]);
 useEffect(()=>{const d=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();if(['a','d','arrowleft','arrowright',' '].includes(k))e.preventDefault();keys.current.add(k);if(k===' ')fire();if(k==='enter'&&state.current!=='play')reset(true)};const u=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());addEventListener('keydown',d);addEventListener('keyup',u);return()=>{removeEventListener('keydown',d);removeEventListener('keyup',u)}},[fire,reset]);
 useEffect(()=>{trackGame('game_open','asteroid-blaster');const c=canvas.current,ctx=c?.getContext('2d');if(!c||!ctx)return;const resize=()=>{const dpr=Math.min(devicePixelRatio||1,2);c.width=W*dpr;c.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)};resize();addEventListener('resize',resize);let last=performance.now();const loop=(now:number)=>{const dt=Math.min(2,(now-last)/16.67||1);last=now;if(state.current==='play'){const k=keys.current;ship.current.x+=((k.has('d')||k.has('arrowright')?7:0)-(k.has('a')||k.has('arrowleft')?7:0))*dt;ship.current.x=Math.max(28,Math.min(W-28,ship.current.x));if(spawn.current++>Math.max(12,42-scoreRef.current*.35)){spawn.current=0;const r=12+Math.random()*22;rocks.current.push({x:30+Math.random()*(W-60),y:-r,vx:(Math.random()-.5)*1.8,vy:2.2+Math.random()*2.4+scoreRef.current*.015,r})}for(const r of rocks.current){r.x+=r.vx*dt;r.y+=r.vy*dt;if(r.x<r.r||r.x>W-r.r)r.vx*=-1}for(const b of bullets.current)b.y+=b.vy*dt;bullets.current=bullets.current.filter(b=>b.y>-20);for(let i=rocks.current.length-1;i>=0;i--){const r=rocks.current[i];if(r.y>H+40){rocks.current.splice(i,1);continue}for(let j=bullets.current.length-1;j>=0;j--){const b=bullets.current[j];if(Math.hypot(b.x-r.x,b.y-r.y)<r.r+7){bullets.current.splice(j,1);rocks.current.splice(i,1);scoreRef.current++;setScore(scoreRef.current);break}}if(rocks.current[i]===r&&Math.hypot(ship.current.x-r.x,H-62-r.y)<r.r+18){state.current='over';setUi('over');setBest(v=>Math.max(v,scoreRef.current));trackGame('game_finish','asteroid-blaster',{score:scoreRef.current})}}}
 ctx.clearRect(0,0,W,H);ctx.fillStyle='#070b12';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#182536';ctx.lineWidth=2;for(let x=0;x<W;x+=45){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=45){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.fillStyle='#78e4ff';ctx.beginPath();ctx.moveTo(ship.current.x,H-92);ctx.lineTo(ship.current.x-25,H-42);ctx.lineTo(ship.current.x,H-52);ctx.lineTo(ship.current.x+25,H-42);ctx.closePath();ctx.fill();ctx.fillStyle='#b7f34a';for(const b of bullets.current)ctx.fillRect(b.x-3,b.y,6,18);for(const r of rocks.current){ctx.strokeStyle='#c6ccd4';ctx.lineWidth=3;ctx.beginPath();for(let i=0;i<7;i++){const a=i*Math.PI*2/7,rr=r.r*(.78+Math.sin(i*3.7)*.12);const x=r.x+Math.cos(a)*rr,y=r.y+Math.sin(a)*rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.stroke()}ctx.fillStyle='#fff';ctx.font='700 24px system-ui';ctx.fillText(String(scoreRef.current),W/2-7,38);raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>{removeEventListener('resize',resize);if(raf.current)cancelAnimationFrame(raf.current)}},[]);
 const move=(dir:number)=>{ship.current.x+=dir*28;ship.current.x=Math.max(28,Math.min(W-28,ship.current.x))};
 return <main className="asteroid-page"><div className="asteroid-shell"><header><a href="/gamehub/">← GAMEHUB</a><span>ARCADE · SHOOTER</span><button onClick={()=>reset(true)}>RESTART</button></header><div className="asteroid-score"><strong>{score}</strong><span>BEST {best}</span></div><div className="asteroid-stage"><canvas ref={canvas} width={W} height={H} aria-label="Asteroid Blaster game" onPointerDown={fire}/>{ui!=='play'&&<div className="asteroid-overlay"><span>☄️</span><h1>{ui==='ready'?'ASTEROID BLASTER':'GAME OVER'}</h1><p>{ui==='ready'?'Move, shoot and survive the falling rocks.':'Score '+score+'. Beat your best.'}</p><button onClick={()=>reset(true)}>{ui==='ready'?'START GAME':'PLAY AGAIN'}</button></div>}</div><div className="asteroid-controls"><button onPointerDown={()=>move(-1)} aria-label="Move left">←</button><button onPointerDown={fire} aria-label="Fire">FIRE</button><button onPointerDown={()=>move(1)} aria-label="Move right">→</button></div><p>MOVE A / D OR ARROWS · SPACE / FIRE TO SHOOT</p></div></main>
}
