'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import './racing-duel.css';
import { trackGame } from '../lib/analytics';

type Car={x:number,y:number,vx:number,vy:number,speed:number,lap:number,boost:number};
const W=900,H=540,FINISH_Y=78,LAPS=3;
const initialCars=():[Car,Car]=>[{x:330,y:H-80,vx:0,vy:0,speed:0,lap:0,boost:100},{x:570,y:H-80,vx:0,vy:0,speed:0,lap:0,boost:100}];

export default function RacingDuel(){
 const canvas=useRef<HTMLCanvasElement>(null),keys=useRef(new Set<string>()),cars=useRef(initialCars()),phase=useRef<'ready'|'play'|'over'>('ready'),raf=useRef<number>(0),last=useRef(0),lapY=useRef([H-80,H-80]);
 const [state,setState]=useState(phase.current),[laps,setLaps]=useState<[number,number]>([0,0]),[winner,setWinner]=useState(0),[message,setMessage]=useState('First to 3 laps wins');
 const reset=useCallback((start=true)=>{cars.current=initialCars();phase.current=start?'play':'ready';setState(phase.current);setLaps([0,0]);setWinner(0);setMessage('First to 3 laps wins');lapY.current=[H-80,H-80];trackGame(start?'game_restart':'game_open','racing-duel')},[]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();if(['a','d','w','s','arrowleft','arrowright','arrowup','arrowdown','shift','enter',' '].includes(k))e.preventDefault();keys.current.add(k);if((k==='enter'||k===' ')&&phase.current!=='play')reset(true)};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());addEventListener('keydown',down);addEventListener('keyup',up);return()=>{removeEventListener('keydown',down);removeEventListener('keyup',up)}},[reset]);
 useEffect(()=>{trackGame('game_open','racing-duel');const c=canvas.current,ctx=c?.getContext('2d');if(!c||!ctx)return;last.current=performance.now();const loop=(now:number)=>{const dt=Math.min(2,(now-last.current)/16.67||1);last.current=now;const ps=cars.current,k=keys.current;
  if(phase.current==='play') ps.forEach((p,i)=>{const left=i===0?'a':'arrowleft',right=i===0?'d':'arrowright',up=i===0?'w':'arrowup',down=i===0?'s':'arrowdown',boost=i===0?'shift':'enter';const steer=(k.has(right)?1:0)-(k.has(left)?1:0);const throttle=(k.has(up)?1:0)-(k.has(down)?.55:0);p.vx+=steer*.42*dt;p.vx*=Math.pow(.91,dt);p.speed+=throttle*.18*dt;p.speed*=Math.pow(.985,dt);if(k.has(boost)&&p.boost>0&&p.speed>1){p.speed+=.34*dt;p.boost=Math.max(0,p.boost-.9*dt)}else p.boost=Math.min(100,p.boost+.12*dt);p.speed=Math.max(0,Math.min(8.2,p.speed));p.x+=p.vx*p.speed*dt;p.y-=p.speed*dt;p.x=Math.max(205,Math.min(W-205,p.x));if(p.y<FINISH_Y){p.lap+=1;p.y=H-90;p.x=i===0?330:570;setLaps([ps[0].lap,ps[1].lap]);setMessage(`PLAYER ${i+1} CLEARS LAP ${p.lap}!`);if(p.lap>=LAPS){phase.current='over';setState('over');setWinner(i+1);setMessage(`PLAYER ${i+1} WINS!`);trackGame('game_finish','racing-duel',{winner:i+1,laps:LAPS})}}});
  ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#121821');g.addColorStop(1,'#07090d');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#1a2029';ctx.fillRect(170,0,560,H);ctx.fillStyle='#242b35';ctx.fillRect(205,0,490,H);ctx.strokeStyle='#4b5666';ctx.lineWidth=4;ctx.strokeRect(205,0,490,H);ctx.setLineDash([28,24]);ctx.strokeStyle='#7e8794';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(W/2,0);ctx.lineTo(W/2,H);ctx.stroke();ctx.setLineDash([]);for(let y=0;y<H;y+=54){ctx.fillStyle='#f7f9fc';ctx.fillRect(205,y,14,28);ctx.fillRect(681,y+27,14,28)}ctx.fillStyle='#b7f34a';ctx.fillRect(205,FINISH_Y,490,8);ctx.fillStyle='#f7f9fc';ctx.font='900 12px Arial';ctx.textAlign='center';ctx.fillText('FINISH',W/2,FINISH_Y-12);drawCar(ctx,ps[0],1);drawCar(ctx,ps[1],2);raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf.current)},[]);
 return <main className="race-page"><div className="race-shell"><header><a href="/gamehub/">← GAMEHUB</a><div><span>2 PLAYER · RACING</span><h1>🏁 RACING DUEL</h1></div><button onClick={()=>reset(true)}>REMATCH</button></header><div className="race-score"><div><small>P1 · {laps[0]}/{LAPS} LAPS</small><strong>{Math.min(laps[0],LAPS)}</strong></div><b>VS</b><div><small>P2 · {laps[1]}/{LAPS} LAPS</small><strong>{Math.min(laps[1],LAPS)}</strong></div></div><div className="race-track"><canvas ref={canvas} width={W} height={H}/>{state!=='play'&&<div className="race-overlay"><span>{state==='ready'?'🏁':winner===1?'🥇':'🥈'}</span><h2>{state==='ready'?'RACING DUEL':`PLAYER ${winner} WINS`}</h2><p>{state==='ready'?'Three laps. Tight corners. One device.':`${laps[0]} — ${laps[1]} · Rematch and settle it again.`}</p><button onClick={()=>reset(true)}>{state==='ready'?'START RACE':'PLAY AGAIN'}</button></div>}</div><div className="race-controls"><div><strong>P1</strong><span>W / S DRIVE</span><span>A / D STEER</span><span>SHIFT BOOST</span></div><div><strong>P2</strong><span>↑ / ↓ DRIVE</span><span>← / → STEER</span><span>ENTER BOOST</span></div></div><p className="race-tip">Hold drive to build speed, steer smoothly, and save your boost for the final lap.</p></div></main>;
}
function drawCar(ctx:CanvasRenderingContext2D,p:Car,who:1|2){ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle=who===1?'#b7f34a':'#78e4ff';ctx.shadowBlur=16;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.roundRect(-17,-30,34,60,9);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#10151d';ctx.fillRect(-11,-16,22,15);ctx.fillRect(-11,7,22,8);ctx.fillStyle='#f7f9fc';ctx.fillRect(-21,-21,5,14);ctx.fillRect(16,-21,5,14);ctx.fillRect(-21,8,5,14);ctx.fillRect(16,8,5,14);ctx.restore()}
