'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import './hoop-duel.css';
import {trackGame} from '../lib/analytics';
import TwoPlayerTouchControls,{TouchAction} from '../TwoPlayerTouchControls';

type Player={x:number;y:number;vx:number;vy:number;facing:number;score:number};type Ball={x:number;y:number;vx:number;vy:number;owner:1|2|null};type Mode='1p'|'2p';
const W=900,H=520,FLOOR=454,PLAYER_W=34,PLAYER_H=58,GRAVITY=.34,WIN_SCORE=7;
const initialPlayers=():[Player,Player]=>[{x:115,y:FLOOR-PLAYER_H,vx:0,vy:0,facing:1,score:0},{x:751,y:FLOOR-PLAYER_H,vx:0,vy:0,facing:-1,score:0}];
const initialBall=():Ball=>({x:W/2,y:260,vx:0,vy:0,owner:null});

export default function HoopDuelPage(){
 const canvasRef=useRef<HTMLCanvasElement|null>(null),keys=useRef(new Set<string>()),players=useRef<[Player,Player]>(initialPlayers()),ball=useRef<Ball>(initialBall()),raf=useRef<number|null>(null),last=useRef(0),state=useRef<'ready'|'playing'|'over'>('ready'),mode=useRef<Mode>('2p');
 const[phase,setPhase]=useState<'ready'|'playing'|'over'>('ready'),[scores,setScores]=useState<[number,number]>([0,0]),[winner,setWinner]=useState(0),[message,setMessage]=useState('First to 7 wins'),[selectedMode,setSelectedMode]=useState<Mode>('2p');
 const reset=useCallback((startNow=true,nextMode:Mode=mode.current)=>{mode.current=nextMode;setSelectedMode(nextMode);players.current=initialPlayers();ball.current=initialBall();state.current=startNow?'playing':'ready';setPhase(state.current);setScores([0,0]);setWinner(0);setMessage(nextMode==='1p'?'Beat the CPU · first to 7':'First to 7 wins');trackGame(startNow?'game_restart':'game_open','hoop-duel',{mode:nextMode})},[]);
 const shoot=useCallback((who:1|2)=>{if(state.current!=='playing')return;const p=players.current[who-1],b=ball.current,near=Math.hypot(b.x-(p.x+PLAYER_W/2),b.y-(p.y+20))<72;if(b.owner!==who&&!near)return;const dir=who===1?1:-1;b.owner=null;b.x=p.x+PLAYER_W/2+dir*24;b.y=p.y+17;b.vx=dir*(7.2+Math.min(2.5,Math.abs(p.vx)*.25));b.vy=-8.4;setMessage(`PLAYER ${who} SHOOTING!`)},[]);
 const touchPress=useCallback((who:1|2,action:TouchAction)=>{if(who===2&&mode.current==='1p')return;if(state.current!=='playing'){if(action==='action'||action==='boost')reset(true,mode.current);return}if(action==='action'||action==='boost'){shoot(who);return}const map=who===1?{left:'a',right:'d',up:'w',down:'s'}:{left:'arrowleft',right:'arrowright',up:'arrowup',down:'arrowdown'};keys.current.add(map[action as keyof typeof map])},[reset,shoot]);
 const touchRelease=useCallback((who:1|2,action:TouchAction)=>{if(who===2&&mode.current==='1p')return;const map=who===1?{left:'a',right:'d',up:'w',down:'s'}:{left:'arrowleft',right:'arrowright',up:'arrowup',down:'arrowdown'};const key=map[action as keyof typeof map];if(key)keys.current.delete(key)},[]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();if(['a','d','w','f','arrowleft','arrowright','arrowup','l','enter',' '].includes(k))e.preventDefault();if(k==='f')shoot(1);if(k==='l'&&mode.current==='2p')shoot(2);keys.current.add(k);if((k==='enter'||k===' ')&&state.current!=='playing')reset(true,mode.current)},up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[reset,shoot]);
 useEffect(()=>{trackGame('game_open','hoop-duel');const c=canvasRef.current,ctx=c?.getContext('2d');if(!c||!ctx)return;last.current=performance.now();const drawHoop=(c:CanvasRenderingContext2D,x:number,side:-1|1)=>{c.fillStyle='#d7dde5';c.fillRect(x-(side<0?0:8),258,8,104);const rimX=side<0?x+8:x-58;c.strokeStyle='#ff7655';c.lineWidth=7;c.beginPath();c.moveTo(rimX,303);c.lineTo(rimX+50,303);c.stroke();c.strokeStyle='#dce4ee';c.lineWidth=2;c.strokeRect(rimX+7,307,41,37)};const drawPlayer=(c:CanvasRenderingContext2D,p:Player,no:1|2)=>{c.save();c.fillStyle=no===1?'#b7f34a':'#78e4ff';c.fillRect(p.x,p.y+16,PLAYER_W,PLAYER_H-16);c.beginPath();c.arc(p.x+PLAYER_W/2,p.y+9,12,0,Math.PI*2);c.fill();c.fillStyle='#0a0d11';c.fillRect(p.x+(p.facing>0?23:3),p.y+5,4,4);c.restore()};const draw=()=>{ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#162435');g.addColorStop(1,'#080b10');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#172231';ctx.fillRect(0,FLOOR,W,H-FLOOR);ctx.strokeStyle='#344153';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(W/2,0);ctx.lineTo(W/2,FLOOR);ctx.stroke();ctx.strokeStyle='#293648';ctx.beginPath();ctx.moveTo(0,FLOOR);ctx.lineTo(W,FLOOR);ctx.stroke();drawHoop(ctx,46,-1);drawHoop(ctx,W-46,1);drawPlayer(ctx,players.current[0],1);drawPlayer(ctx,players.current[1],2);const b=ball.current;ctx.beginPath();ctx.arc(b.x,b.y,11,0,Math.PI*2);ctx.fillStyle='#f28a3d';ctx.fill();ctx.fillStyle='#ffffffaa';ctx.font='800 11px DM Sans';ctx.textAlign='center';ctx.fillText('P1',72,28);ctx.fillText(mode.current==='1p'?'CPU':'P2',W-72,28)};
 const tick=(time:number)=>{const dt=Math.min(2,(time-last.current)/16.67||1);last.current=time;if(state.current==='playing'){const[p1,p2]=players.current,k=keys.current;[p1,p2].forEach((p,i)=>{const left=i?'arrowleft':'a',right=i?'arrowright':'d',jump=i?'arrowup':'w';if(i===1&&mode.current==='1p'){const target=ball.current.x;const center=p.x+PLAYER_W/2;p.vx=target<center-18?-3.5:target>center+18?3.5:0;if(ball.current.y<p.y+35&&Math.random()<.08)k.add('arrowup');else if(ball.current.y>=p.y+35)k.delete('arrowup')}else{p.vx=0;if(k.has(left))p.vx=-4.2;if(k.has(right))p.vx=4.2}if(p.vx!==0)p.facing=p.vx>0?1:-1;if(k.has(jump)&&p.y>=FLOOR-PLAYER_H-1)p.vy=-8.3;p.vy+=GRAVITY*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.x=Math.max(12,Math.min(W-PLAYER_W-12,p.x));if(p.y>FLOOR-PLAYER_H){p.y=FLOOR-PLAYER_H;p.vy=0}});const b=ball.current;if(!b.owner){b.vy+=GRAVITY*.95*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;b.vx*=Math.pow(.994,dt);if(b.y>FLOOR-11){b.y=FLOOR-11;b.vy*=-.55;if(Math.abs(b.vy)<1)b.vy=0}if(b.x<14||b.x>W-14){b.x=Math.max(14,Math.min(W-14,b.x));b.vx*=-.7}[p1,p2].forEach((p,i)=>{const dx=b.x-(p.x+PLAYER_W/2),dy=b.y-(p.y+22);if(Math.hypot(dx,dy)<42&&b.vy>-1){b.owner=(i+1)as 1|2;b.vx=0;b.vy=0;b.x=p.x+PLAYER_W/2+p.facing*27;b.y=p.y+20}});[{x:58,scoreFor:2},{x:W-58,scoreFor:1}].forEach(h=>{if(b.x>h.x-28&&b.x<h.x+28&&b.y>298&&b.y<314&&b.vy>0){const scorer=h.scoreFor as 1|2;players.current[scorer-1].score++;const next=players.current.map(p=>p.score)as[number,number];setScores(next);if(next[scorer-1]>=WIN_SCORE){state.current='over';setPhase('over');setWinner(scorer);setMessage(`PLAYER ${scorer} WINS!`);trackGame('game_finish','hoop-duel',{scorer,winner:scorer,mode:mode.current})}else{b.x=W/2;b.y=230;b.vx=0;b.vy=0;b.owner=null;setMessage(`PLAYER ${scorer} SCORES!`)}}})}else{const p=players.current[b.owner-1];b.x=p.x+PLAYER_W/2+p.facing*27;b.y=p.y+20}}draw();raf.current=requestAnimationFrame(tick)};raf.current=requestAnimationFrame(tick);return()=>{if(raf.current)cancelAnimationFrame(raf.current)}},[]);
 return <main className="hoop-page"><div className="hoop-shell"><header className="hoop-top"><a href="/gamehub/multiplayer/" className="back">← Multiplayer</a><div><span>2 PLAYER · SPORTS</span><h1>🏀 HOOP DUEL</h1></div><div className="scoreboard"><b>{scores[0]}</b><i>:</i><b>{scores[1]}</b></div></header><section className="hoop-card"><div className="hoop-info"><span>LOCAL ARCADE</span><strong>{message}</strong><small>{selectedMode==='1p'?'P1 vs CPU · one-button touch mode':'P1 left · P2 right · simultaneous touch'}</small></div><div className="court-wrap"><canvas ref={canvasRef} width={W} height={H} aria-label="Basketball duel court"/>{phase!=='playing'&&<div className="hoop-overlay"><span className="overlay-icon">🏀</span><h2>{phase==='over'?`PLAYER ${winner} WINS!`:'HOOP DUEL'}</h2><p>{phase==='over'?`${scores[0]} — ${scores[1]} · Rematch instantly.`:'Chaotic basketball. Simple controls. Best of seven.'}</p>{phase!=='over'&&<div className="mode-row"><button className={selectedMode==='1p'?'mode active':'mode'} onClick={()=>{mode.current='1p';setSelectedMode('1p')}}>1 PLAYER<br/><small>VS CPU</small></button><button className={selectedMode==='2p'?'mode active':'mode'} onClick={()=>{mode.current='2p';setSelectedMode('2p')}}>2 PLAYERS<br/><small>LOCAL</small></button></div>}<button className="primary" onClick={()=>reset(true,selectedMode)}>{phase==='over'?'REMATCH':'START DUEL'}</button></div>}</div><div className="quick-touch" aria-label="Quick touch controls"><button onPointerDown={e=>{e.preventDefault();touchPress(1,'action')}} onPointerUp={e=>{e.preventDefault();touchRelease(1,'action')}} onPointerCancel={e=>touchRelease(1,'action')}><span>P1</span><strong>HOLD / TAP</strong><small>LEFT SIDE</small></button><button disabled={selectedMode==='1p'} onPointerDown={e=>{e.preventDefault();touchPress(2,'action')}} onPointerUp={e=>{e.preventDefault();touchRelease(2,'action')}} onPointerCancel={e=>touchRelease(2,'action')}><span>{selectedMode==='1p'?'CPU':'P2'}</span><strong>{selectedMode==='1p'?'CPU PLAYING':'HOLD / TAP'}</strong><small>RIGHT SIDE</small></button></div><TwoPlayerTouchControls onPress={touchPress} onRelease={touchRelease} actionLabel="SHOOT" actionLabel2="SHOOT" upLabel="JUMP"/><p className="hoop-note">Quick touch is the simple mode: hold or tap your own side. Full controls stay available below.</p></section></div></main>;
}
