'use client';
import {useCallback,useEffect,useRef,useState} from 'react';import './air-hockey.css';import {trackGame} from '../lib/analytics';import TwoPlayerTouchControls,{TouchAction} from '../TwoPlayerTouchControls';
const W=900,H=520,R=22,WIN=7;type P={x:number,y:number};type Disk={x:number,y:number,vx:number,vy:number};
const resetP=():[P,P]=>[{x:130,y:H/2},{x:W-130,y:H/2}];const resetD=():Disk=>({x:W/2,y:H/2,vx:5,vy:2});
export default function AirHockey(){const c=useRef<HTMLCanvasElement>(null),keys=useRef(new Set<string>()),ps=useRef(resetP()),d=useRef(resetD()),phase=useRef<'ready'|'play'|'serve'|'over'>('ready'),serveUntil=useRef(0),servePlayer=useRef<1|2>(1),raf=useRef(0),scoreRef=useRef<[number,number]>([0,0]);const[state,setState]=useState(phase.current),[score,setScore]=useState<[number,number]>([0,0]),[winner,setWinner]=useState(0);
 const restart=useCallback((start=true)=>{ps.current=resetP();d.current=resetD();phase.current=start?'play':'ready';serveUntil.current=0;servePlayer.current=1;scoreRef.current=[0,0];setState(phase.current);setScore([0,0]);setWinner(0);trackGame(start?'game_restart':'game_open','air-hockey')},[]);
 const keyFor=(player:1|2,action:TouchAction)=>player===1?({left:'a',right:'d',up:'w',down:'s',action:'enter',boost:'enter'} as Record<TouchAction,string>)[action]:({left:'arrowleft',right:'arrowright',up:'arrowup',down:'arrowdown',action:' ',boost:' ' } as Record<TouchAction,string>)[action];
 const touchPress=useCallback((player:1|2,action:TouchAction)=>{if(phase.current!=='play'){if((phase.current==='ready'||phase.current==='over')&&action==='action')restart(true);return;}keys.current.add(keyFor(player,action));},[restart]);
 const touchRelease=useCallback((player:1|2,action:TouchAction)=>{keys.current.delete(keyFor(player,action));},[]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','enter',' '].includes(k))e.preventDefault();keys.current.add(k);if((k==='enter'||k===' ')&&(phase.current==='ready'||phase.current==='over'))restart(true)};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());addEventListener('keydown',down);addEventListener('keyup',up);return()=>{removeEventListener('keydown',down);removeEventListener('keyup',up)}},[restart]);
 useEffect(()=>{trackGame('game_open','air-hockey');const x=c.current,ctx=x?.getContext('2d');if(!x||!ctx)return;let last=performance.now();const loop=(now:number)=>{const dt=Math.min(2,(now-last)/16.67);last=now;const p=ps.current,b=d.current,k=keys.current;if(phase.current==='serve'){if(now>=serveUntil.current){phase.current='play';setState('play');b.x=W/2;b.y=H/2;b.vx=servePlayer.current===1?-5:5;b.vy=(Math.random()-.5)*4}}else if(phase.current==='play'){p[0].x+=((k.has('d')?5:0)-(k.has('a')?5:0))*dt;p[0].y+=((k.has('s')?5:0)-(k.has('w')?5:0))*dt;p[1].x+=((k.has('arrowright')?5:0)-(k.has('arrowleft')?5:0))*dt;p[1].y+=((k.has('arrowdown')?5:0)-(k.has('arrowup')?5:0))*dt;p[0].x=Math.max(45,Math.min(W/2-35,p[0].x));p[1].x=Math.max(W/2+35,Math.min(W-45,p[1].x));p.forEach(v=>v.y=Math.max(55,Math.min(H-55,v.y)));b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.y<R||b.y>H-R){b.y=Math.max(R,Math.min(H-R,b.y));b.vy*=-1}for(const q of p){const dx=b.x-q.x,dy=b.y-q.y,dist=Math.hypot(dx,dy);if(dist<R+26){const nx=dx/(dist||1),ny=dy/(dist||1);b.x=q.x+nx*(R+27);b.y=q.y+ny*(R+27);const speed=Math.min(13,Math.hypot(b.vx,b.vy)+.25);b.vx=nx*speed;b.vy=ny*speed}}if(b.x<-R){p[1].x=W-130;p[1].y=H/2;const next:[number,number]=[scoreRef.current[0],scoreRef.current[1]+1];scoreRef.current=next;setScore(next);navigator.vibrate?.(45);if(next[1]>=WIN){phase.current='over';setState('over');setWinner(2);trackGame('game_finish','air-hockey',{winner:2})}else{servePlayer.current=2;phase.current='serve';serveUntil.current=now+650;setState('serve')}}if(b.x>W+R){p[0].x=130;p[0].y=H/2;const next:[number,number]=[scoreRef.current[0]+1,scoreRef.current[1]];scoreRef.current=next;setScore(next);navigator.vibrate?.(45);if(next[0]>=WIN){phase.current='over';setState('over');setWinner(1);trackGame('game_finish','air-hockey',{winner:1})}else{servePlayer.current=1;phase.current='serve';serveUntil.current=now+650;setState('serve')}}}
 ctx.clearRect(0,0,W,H);ctx.fillStyle='#0b1118';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#78e4ff';ctx.lineWidth=3;ctx.strokeRect(18,18,W-36,H-36);ctx.beginPath();ctx.moveTo(W/2,18);ctx.lineTo(W/2,H-18);ctx.stroke();ctx.beginPath();ctx.arc(W/2,H/2,72,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#b7f34a';ctx.beginPath();ctx.arc(p[0].x,p[0].y,27,0,Math.PI*2);ctx.fill();ctx.fillStyle='#78e4ff';ctx.beginPath();ctx.arc(p[1].x,p[1].y,27,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(b.x,b.y,R,0,Math.PI*2);ctx.fill();raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf.current)},[restart]);
 return <main className="air-page"><div className="air-shell"><header><a href="/gamehub/">← GAMEHUB</a><span>2 PLAYER · AIR HOCKEY</span><button onClick={()=>restart(true)}>REMATCH</button></header><div className="air-score" aria-live="polite" aria-label={`Score ${score[0]} to ${score[1]}`}><strong>{score[0]}</strong><span>FIRST TO {WIN}</span><strong>{score[1]}</strong></div><div className="air-stage"><canvas ref={c} width={W} height={H} aria-label="Air hockey table for two players"/>{state!=='play'&&<div className="air-overlay"><span>{state==='ready'?'🏒':state==='serve'?'🏒':winner===1?'🥇':'🥈'}</span><h1>{state==='ready'?'AIR HOCKEY DUEL':state==='serve'?`PLAYER ${servePlayer.current} SERVES`:`PLAYER ${winner} WINS`}</h1><p>{state==='serve'?`Get ready · Score ${score[0]}–${score[1]}`:`Fast hands. First to ${WIN} goals.`}</p><button onClick={()=>restart(true)}>{state==='ready'?'START MATCH':state==='serve'?'GET READY':'PLAY AGAIN'}</button></div>}</div><TwoPlayerTouchControls onPress={touchPress} onRelease={touchRelease} actionLabel="START" actionLabel2="START" upLabel="↑" showDown /><p className="air-tip">Two hands, one screen: hold any direction and both players can move together.</p></div></main>}
