'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import './asteroid-blaster.css';
import {trackGame} from '../lib/analytics';
import AsteroidTouchControls from './AsteroidTouchControls';

type State='ready'|'play'|'over';
type Asteroid={x:number;y:number;vx:number;vy:number;r:number};
type Bullet={x:number;y:number;vy:number};
type Particle={x:number;y:number;vx:number;vy:number;life:number;r:number};
const W=900,H=520;

export default function AsteroidBlaster(){
 const canvas=useRef<HTMLCanvasElement>(null),keys=useRef(new Set<string>()),ship=useRef({x:W/2,y:H-62}),rocks=useRef<Asteroid[]>([]),bullets=useRef<Bullet[]>([]),particles=useRef<Particle[]>([]),scoreRef=useRef(0),state=useRef<State>('ready'),spawn=useRef(0),raf=useRef<number|undefined>(undefined),fireHeld=useRef(false),lastShot=useRef(0),stick=useRef({x:0,y:0}),waveRef=useRef(1);
 const [ui,setUi]=useState<State>('ready'),[score,setScore]=useState(0),[best,setBest]=useState(0),[wave,setWave]=useState(1);
 const reset=useCallback((start=true)=>{ship.current={x:W/2,y:H-62};rocks.current=[];bullets.current=[];particles.current=[];scoreRef.current=0;spawn.current=0;fireHeld.current=false;lastShot.current=0;stick.current={x:0,y:0};waveRef.current=1;state.current=start?'play':'ready';setUi(state.current);setScore(0);setWave(1);if(start)trackGame('game_restart','asteroid-blaster')},[]);
 const fire=useCallback(()=>{if(state.current!=='play'){reset(true);return}const now=performance.now();if(now-lastShot.current<105)return;lastShot.current=now;bullets.current.push({x:ship.current.x,y:ship.current.y-30,vy:-11})},[reset]);
 const startFire=useCallback(()=>{fireHeld.current=true;fire()},[fire]);
 const stopFire=useCallback(()=>{fireHeld.current=false},[]);
 const joystick=useCallback((x:number,y:number)=>{if(state.current!=='play'){reset(true);return}stick.current={x,y}},[reset]);
 const stopJoystick=useCallback(()=>{stick.current={x:0,y:0}},[]);
 useEffect(()=>{const d=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();if(['a','d','w','s','arrowleft','arrowright','arrowup','arrowdown',' '].includes(k))e.preventDefault();keys.current.add(k);if(k===' '){fireHeld.current=true;fire()}if(k==='enter'&&state.current!=='play')reset(true)},u=(e:KeyboardEvent)=>{keys.current.delete(e.key.toLowerCase());if(e.key===' ')fireHeld.current=false};addEventListener('keydown',d);addEventListener('keyup',u);return()=>{removeEventListener('keydown',d);removeEventListener('keyup',u)}},[fire,reset]);
 useEffect(()=>{trackGame('game_open','asteroid-blaster');const c=canvas.current,ctx=c?.getContext('2d');if(!c||!ctx)return;const resize=()=>{const dpr=Math.min(devicePixelRatio||1,2);c.width=W*dpr;c.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)};resize();addEventListener('resize',resize);let last=performance.now();const loop=(now:number)=>{const dt=Math.min(2,(now-last)/16.67||1);last=now;const currentWave=Math.floor(scoreRef.current/10)+1;if(state.current==='play'){const k=keys.current;const keyboardX=(k.has('d')||k.has('arrowright')?1:0)-(k.has('a')||k.has('arrowleft')?1:0);const keyboardY=(k.has('s')||k.has('arrowdown')?1:0)-(k.has('w')||k.has('arrowup')?1:0);const ix=keyboardX||stick.current.x,iy=keyboardY||stick.current.y;ship.current.x+=ix*7.5*dt;ship.current.y+=iy*5.5*dt;ship.current.x=Math.max(28,Math.min(W-28,ship.current.x));ship.current.y=Math.max(H*.42,Math.min(H-42,ship.current.y));if(fireHeld.current)fire();if(currentWave!==waveRef.current){waveRef.current=currentWave;setWave(currentWave)}const interval=Math.max(9,40-currentWave*2.2);if(spawn.current++>interval){spawn.current=0;const r=12+Math.random()*22;rocks.current.push({x:30+Math.random()*(W-60),y:-r,vx:(Math.random()-.5)*(1.6+currentWave*.05),vy:2.1+Math.random()*2.2+currentWave*.12,r})}for(const r of rocks.current){r.x+=r.vx*dt;r.y+=r.vy*dt;if(r.x<r.r||r.x>W-r.r)r.vx*=-1}for(const b of bullets.current)b.y+=b.vy*dt;bullets.current=bullets.current.filter(b=>b.y>-20);for(const p of particles.current){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.98;p.vy*=.98;p.life-=.045*dt}particles.current=particles.current.filter(p=>p.life>0);for(let i=rocks.current.length-1;i>=0;i--){const r=rocks.current[i];if(r.y>H+40){rocks.current.splice(i,1);continue}for(let j=bullets.current.length-1;j>=0;j--){const b=bullets.current[j];if(Math.hypot(b.x-r.x,b.y-r.y)<r.r+7){bullets.current.splice(j,1);rocks.current.splice(i,1);scoreRef.current++;setScore(scoreRef.current);for(let p=0;p<10;p++){const a=Math.random()*Math.PI*2,s=1+Math.random()*3;particles.current.push({x:r.x,y:r.y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:1,r:1+Math.random()*2})}break}}if(rocks.current[i]===r&&Math.hypot(ship.current.x-r.x,ship.current.y-r.y)<r.r+18){state.current='over';fireHeld.current=false;stick.current={x:0,y:0};setUi('over');setBest(v=>{const n=Math.max(v,scoreRef.current);localStorage.setItem('gamehub:asteroid-blaster-best',String(n));return n});trackGame('game_finish','asteroid-blaster',{score:scoreRef.current,wave:currentWave});break}}}
 ctx.clearRect(0,0,W,H);ctx.fillStyle='#070b12';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#182536';ctx.lineWidth=2;for(let x=0;x<W;x+=45){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=45){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(const p of particles.current){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle='#b7f34a';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.fillStyle='#78e4ff';ctx.beginPath();ctx.moveTo(ship.current.x,ship.current.y-30);ctx.lineTo(ship.current.x-25,ship.current.y+20);ctx.lineTo(ship.current.x,ship.current.y+10);ctx.lineTo(ship.current.x+25,ship.current.y+20);ctx.closePath();ctx.fill();ctx.fillStyle='#b7f34a';for(const b of bullets.current)ctx.fillRect(b.x-3,b.y,6,18);for(const r of rocks.current){ctx.strokeStyle='#c6ccd4';ctx.lineWidth=3;ctx.beginPath();for(let i=0;i<7;i++){const a=i*Math.PI*2/7,rr=r.r*(.78+Math.sin(i*3.7)*.12),x=r.x+Math.cos(a)*rr,y=r.y+Math.sin(a)*rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.stroke()}ctx.fillStyle='#fff';ctx.font='700 24px system-ui';ctx.fillText(String(scoreRef.current),W/2-7,38);ctx.font='700 11px system-ui';ctx.fillStyle='#84909b';ctx.fillText('WAVE '+currentWave,W/2+28,37);raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>{removeEventListener('resize',resize);if(raf.current!==undefined)cancelAnimationFrame(raf.current)}},[fire]);
 useEffect(()=>{const v=Number(localStorage.getItem('gamehub:asteroid-blaster-best')||0);setBest(v)},[]);
 return <main className="asteroid-page"><div className="asteroid-shell"><header><a href="/gamehub/">← GAMEHUB</a><span>ARCADE · SHOOTER</span><button onClick={()=>reset(true)}>RESTART</button></header><div className="asteroid-score"><strong>{score}</strong><span>BEST {best}</span></div><div className="asteroid-stage"><canvas ref={canvas} width={W} height={H} aria-label="Asteroid Blaster game" />{ui!=='play'&&<div className="asteroid-overlay"><span>☄️</span><h1>{ui==='ready'?'ASTEROID BLASTER':'GAME OVER'}</h1><p>{ui==='ready'?'Move, shoot and survive the falling rocks.':'Score '+score+'. Reach wave '+wave+' and beat your best.'}</p><button onClick={()=>reset(true)}>{ui==='ready'?'START GAME':'PLAY AGAIN'}</button></div>}</div><AsteroidTouchControls onMove={joystick} onStop={stopJoystick} onFireStart={startFire} onFireStop={stopFire}/><p>JOYSTICK TO MOVE · HOLD FIRE FOR AUTO-SHOOT · KEYBOARD: WASD / ARROWS + SPACE</p></div></main>
}
